import type { SoundArchetype } from '../types.ts';

export const ARCHETYPES: SoundArchetype[] = [

  // ── WIND ──────────────────────────────────────────────────────────────────
  {
    name: 'wind-gust',
    frequency: 180,
    waveform: 'triangle',
    attack: 3, decay: 2, sustain: 0.6, release: 5,
    lfoRate: 0.18, lfoDepth: 40, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 600, Q: 1.2 },
  },
  {
    name: 'wind-howl',
    frequency: 260,
    waveform: 'sine',
    attack: 4, decay: 3, sustain: 0.7, release: 6,
    lfoRate: 0.07, lfoDepth: 55, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 400, Q: 2.5 },
  },
  {
    name: 'wind-whisper',
    frequency: 420,
    waveform: 'triangle',
    attack: 5, decay: 1, sustain: 0.5, release: 7,
    lfoRate: 0.35, lfoDepth: 25, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 300, Q: 0.8 },
  },
  {
    name: 'wind-low-drone',
    frequency: 80,
    waveform: 'sine',
    attack: 6, decay: 2, sustain: 0.8, release: 8,
    lfoRate: 0.05, lfoDepth: 12, lfoTarget: 'frequency',
    filter: { type: 'lowpass', freq: 350, Q: 1.0 },
  },

  // ── WATER ─────────────────────────────────────────────────────────────────
  {
    name: 'stream-babble',
    frequency: 680,
    waveform: 'sine',
    attack: 0.5, decay: 0.3, sustain: 0.7, release: 2,
    lfoRate: 3.2, lfoDepth: 90, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 900, Q: 3 },
  },
  {
    name: 'river-flow',
    frequency: 320,
    waveform: 'triangle',
    attack: 2, decay: 1, sustain: 0.8, release: 4,
    lfoRate: 0.6, lfoDepth: 30, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 500, Q: 1.5 },
  },
  {
    name: 'deep-current',
    frequency: 60,
    waveform: 'sine',
    attack: 5, decay: 2, sustain: 0.9, release: 7,
    lfoRate: 0.12, lfoDepth: 8, lfoTarget: 'amplitude',
    filter: { type: 'lowpass', freq: 280, Q: 0.6 },
  },
  {
    name: 'lake-surface',
    frequency: 200,
    waveform: 'sine',
    attack: 3, decay: 1.5, sustain: 0.6, release: 5,
    lfoRate: 0.22, lfoDepth: 18, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 350, Q: 2.0 },
  },
  {
    name: 'waterfall-roar',
    frequency: 140,
    waveform: 'sawtooth',
    attack: 2, decay: 1, sustain: 0.9, release: 4,
    lfoRate: 1.4, lfoDepth: 20, lfoTarget: 'amplitude',
    filter: { type: 'lowpass', freq: 600, Q: 0.7 },
  },

  // ── DROPS ─────────────────────────────────────────────────────────────────
  {
    name: 'rain-drop',
    frequency: 1200,
    waveform: 'sine',
    attack: 0.005, decay: 0.4, sustain: 0.05, release: 0.8,
    lfoRate: 4.5, lfoDepth: 12, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 1400, Q: 6 },
  },
  {
    name: 'rain-gentle',
    frequency: 900,
    waveform: 'sine',
    attack: 0.01, decay: 0.2, sustain: 0.1, release: 0.5,
    lfoRate: 5.8, lfoDepth: 30, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 700, Q: 1.5 },
  },
  {
    name: 'cave-drip',
    frequency: 660,
    waveform: 'sine',
    attack: 0.003, decay: 1.2, sustain: 0.0, release: 1.5,
    lfoRate: 0.4, lfoDepth: 5, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 700, Q: 10 },
  },
  {
    name: 'puddle-plop',
    frequency: 380,
    waveform: 'sine',
    attack: 0.004, decay: 0.7, sustain: 0.0, release: 1.0,
    lfoRate: 0.9, lfoDepth: 8, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 400, Q: 7 },
  },

  // ── INSECTS ───────────────────────────────────────────────────────────────
  {
    name: 'cricket-chirp',
    frequency: 4200,
    waveform: 'square',
    attack: 0.01, decay: 0.06, sustain: 0.4, release: 0.1,
    lfoRate: 14, lfoDepth: 1, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 4200, Q: 12 },
  },
  {
    name: 'cicada-buzz',
    frequency: 3500,
    waveform: 'square',
    attack: 1.5, decay: 0.5, sustain: 0.8, release: 2,
    lfoRate: 18, lfoDepth: 1, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 3500, Q: 8 },
  },
  {
    name: 'bee-drone',
    frequency: 250,
    waveform: 'square',
    attack: 0.3, decay: 0.2, sustain: 0.9, release: 1,
    lfoRate: 0.8, lfoDepth: 15, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 280, Q: 4 },
  },
  {
    name: 'mosquito-whine',
    frequency: 600,
    waveform: 'triangle',
    attack: 0.5, decay: 0.3, sustain: 0.8, release: 1.5,
    lfoRate: 1.1, lfoDepth: 20, lfoTarget: 'frequency',
    filter: { type: 'highpass', freq: 500, Q: 2 },
  },
  {
    name: 'beetle-scrape',
    frequency: 180,
    waveform: 'sawtooth',
    attack: 0.05, decay: 0.15, sustain: 0.3, release: 0.4,
    lfoRate: 6, lfoDepth: 1, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 200, Q: 5 },
  },

  // ── BIRDS ─────────────────────────────────────────────────────────────────
  {
    name: 'songbird-trill',
    frequency: 2800,
    waveform: 'sine',
    attack: 0.05, decay: 0.1, sustain: 0.6, release: 0.3,
    lfoRate: 8, lfoDepth: 200, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 3000, Q: 5 },
  },
  {
    name: 'owl-hoot',
    frequency: 220,
    waveform: 'sine',
    attack: 0.1, decay: 1.5, sustain: 0.3, release: 2.5,
    lfoRate: 0.15, lfoDepth: 10, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 250, Q: 6 },
  },
  {
    name: 'dove-coo',
    frequency: 340,
    waveform: 'sine',
    attack: 0.08, decay: 0.8, sustain: 0.4, release: 1.5,
    lfoRate: 0.6, lfoDepth: 30, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 360, Q: 7 },
  },
  {
    name: 'hawk-cry',
    frequency: 1600,
    waveform: 'sawtooth',
    attack: 0.03, decay: 0.5, sustain: 0.2, release: 1,
    lfoRate: 2.5, lfoDepth: 150, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 1800, Q: 4 },
  },
  {
    name: 'woodpecker-tap',
    frequency: 500,
    waveform: 'triangle',
    attack: 0.003, decay: 0.08, sustain: 0.0, release: 0.15,
    lfoRate: 10, lfoDepth: 1, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 600, Q: 8 },
  },

  // ── TREES & FOLIAGE ───────────────────────────────────────────────────────
  {
    name: 'leaf-rustle',
    frequency: 1800,
    waveform: 'triangle',
    attack: 0.2, decay: 0.4, sustain: 0.5, release: 1.5,
    lfoRate: 2.8, lfoDepth: 60, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 1200, Q: 1 },
  },
  {
    name: 'branch-creak',
    frequency: 140,
    waveform: 'sawtooth',
    attack: 0.1, decay: 0.8, sustain: 0.2, release: 2,
    lfoRate: 0.25, lfoDepth: 25, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 180, Q: 3 },
  },
  {
    name: 'pine-sigh',
    frequency: 520,
    waveform: 'triangle',
    attack: 4, decay: 2, sustain: 0.55, release: 6,
    lfoRate: 0.14, lfoDepth: 35, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 700, Q: 1.8 },
  },
  {
    name: 'bamboo-knock',
    frequency: 360,
    waveform: 'triangle',
    attack: 0.004, decay: 0.6, sustain: 0.0, release: 1.0,
    lfoRate: 1.2, lfoDepth: 5, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 380, Q: 9 },
  },

  // ── EARTH & UNDERGROUND ───────────────────────────────────────────────────
  {
    name: 'earth-rumble',
    frequency: 32,
    waveform: 'sine',
    attack: 6, decay: 3, sustain: 0.8, release: 8,
    lfoRate: 0.04, lfoDepth: 4, lfoTarget: 'amplitude',
    filter: { type: 'lowpass', freq: 100, Q: 0.5 },
  },
  {
    name: 'cave-resonance',
    frequency: 75,
    waveform: 'sine',
    attack: 5, decay: 2, sustain: 0.7, release: 8,
    lfoRate: 0.09, lfoDepth: 6, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 90, Q: 4 },
  },
  {
    name: 'rock-hum',
    frequency: 110,
    waveform: 'triangle',
    attack: 4, decay: 2, sustain: 0.85, release: 7,
    lfoRate: 0.06, lfoDepth: 5, lfoTarget: 'frequency',
    filter: { type: 'lowpass', freq: 220, Q: 1 },
  },

  // ── FIRE & HEAT ───────────────────────────────────────────────────────────
  {
    name: 'fire-crackle',
    frequency: 320,
    waveform: 'sawtooth',
    attack: 0.05, decay: 0.12, sustain: 0.3, release: 0.3,
    lfoRate: 7, lfoDepth: 1, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 200, Q: 0.8 },
  },
  {
    name: 'ember-pulse',
    frequency: 160,
    waveform: 'triangle',
    attack: 1, decay: 0.5, sustain: 0.6, release: 2,
    lfoRate: 0.45, lfoDepth: 20, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 200, Q: 2 },
  },

  // ── NIGHT & ATMOSPHERE ────────────────────────────────────────────────────
  {
    name: 'night-hum',
    frequency: 48,
    waveform: 'sine',
    attack: 6, decay: 2, sustain: 0.9, release: 9,
    lfoRate: 0.03, lfoDepth: 3, lfoTarget: 'amplitude',
    filter: { type: 'lowpass', freq: 160, Q: 0.6 },
  },
  {
    name: 'fog-tone',
    frequency: 170,
    waveform: 'sine',
    attack: 7, decay: 3, sustain: 0.65, release: 9,
    lfoRate: 0.08, lfoDepth: 10, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 220, Q: 1.5 },
  },
  {
    name: 'dawn-shimmer',
    frequency: 1100,
    waveform: 'sine',
    attack: 3, decay: 1.5, sustain: 0.4, release: 5,
    lfoRate: 0.9, lfoDepth: 45, lfoTarget: 'frequency',
    filter: { type: 'highpass', freq: 800, Q: 1 },
  },

  // ── OCEAN & SHORE ─────────────────────────────────────────────────────────
  {
    name: 'wave-surge',
    frequency: 90,
    waveform: 'sine',
    attack: 2.5, decay: 3, sustain: 0.5, release: 5,
    lfoRate: 0.13, lfoDepth: 22, lfoTarget: 'amplitude',
    filter: { type: 'lowpass', freq: 400, Q: 0.9 },
  },
  {
    name: 'tide-wash',
    frequency: 200,
    waveform: 'triangle',
    attack: 3, decay: 4, sustain: 0.4, release: 6,
    lfoRate: 0.1, lfoDepth: 30, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 300, Q: 1.2 },
  },
  {
    name: 'sea-wind',
    frequency: 300,
    waveform: 'triangle',
    attack: 4, decay: 2, sustain: 0.7, release: 6,
    lfoRate: 0.2, lfoDepth: 50, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 500, Q: 1.8 },
  },

  // ── BIOME DRONES ──────────────────────────────────────────────────────────
  {
    name: 'forest-pulse',
    frequency: 55,
    waveform: 'sine',
    attack: 4, decay: 2, sustain: 0.85, release: 7,
    lfoRate: 0.11, lfoDepth: 7, lfoTarget: 'frequency',
    filter: { type: 'lowpass', freq: 300, Q: 0.8 },
  },
  {
    name: 'meadow-tone',
    frequency: 330,
    waveform: 'sine',
    attack: 3, decay: 1, sustain: 0.7, release: 5,
    lfoRate: 0.28, lfoDepth: 18, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 440, Q: 2 },
  },

  // ── RHYTHMIC WATER DROPS (6 VARIANTS) ────────────────────────────────────
  {
    name: 'drop-rhythm-a',
    mode: 'rhythmic',
    frequency: 1450,
    waveform: 'sine',
    attack: 0.004, decay: 0.12, sustain: 0.06, release: 0.22,
    lfoRate: 8.2, lfoDepth: 118, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 1700, Q: 10 },
  },
  {
    name: 'drop-rhythm-b',
    mode: 'rhythmic',
    frequency: 980,
    waveform: 'triangle',
    attack: 0.006, decay: 0.18, sustain: 0.08, release: 0.28,
    lfoRate: 6.1, lfoDepth: 110, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 1200, Q: 8 },
  },
  {
    name: 'drop-rhythm-c',
    mode: 'rhythmic',
    frequency: 1220,
    waveform: 'sine',
    attack: 0.003, decay: 0.08, sustain: 0.03, release: 0.16,
    lfoRate: 9.6, lfoDepth: 130, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 900, Q: 3 },
  },
  {
    name: 'drop-rhythm-d',
    mode: 'rhythmic',
    frequency: 760,
    waveform: 'triangle',
    attack: 0.008, decay: 0.24, sustain: 0.1, release: 0.32,
    lfoRate: 4.4, lfoDepth: 102, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 860, Q: 7 },
  },
  {
    name: 'drop-rhythm-e',
    mode: 'rhythmic',
    frequency: 1680,
    waveform: 'sine',
    attack: 0.003, decay: 0.1, sustain: 0.02, release: 0.14,
    lfoRate: 11.2, lfoDepth: 136, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 1900, Q: 12 },
  },
  {
    name: 'drop-rhythm-f',
    mode: 'rhythmic',
    frequency: 540,
    waveform: 'triangle',
    attack: 0.01, decay: 0.34, sustain: 0.14, release: 0.4,
    lfoRate: 2.9, lfoDepth: 96, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 600, Q: 6 },
  },

  // ── RHYTHMIC CICADAS (6 VARIANTS) ─────────────────────────────────────────
  {
    name: 'cicada-rhythm-a',
    mode: 'rhythmic',
    frequency: 3400,
    waveform: 'square',
    attack: 0.014, decay: 0.12, sustain: 0.22, release: 0.22,
    lfoRate: 12.5, lfoDepth: 122, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 3600, Q: 10 },
  },
  {
    name: 'cicada-rhythm-b',
    mode: 'rhythmic',
    frequency: 2900,
    waveform: 'square',
    attack: 0.02, decay: 0.2, sustain: 0.3, release: 0.35,
    lfoRate: 8.6, lfoDepth: 110, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 3000, Q: 8 },
  },
  {
    name: 'cicada-rhythm-c',
    mode: 'rhythmic',
    frequency: 4100,
    waveform: 'sawtooth',
    attack: 0.012, decay: 0.09, sustain: 0.16, release: 0.18,
    lfoRate: 14.8, lfoDepth: 138, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 4300, Q: 12 },
  },
  {
    name: 'cicada-rhythm-d',
    mode: 'rhythmic',
    frequency: 3200,
    waveform: 'square',
    attack: 0.018, decay: 0.18, sustain: 0.26, release: 0.3,
    lfoRate: 10.2, lfoDepth: 116, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 3300, Q: 9 },
  },
  {
    name: 'cicada-rhythm-e',
    mode: 'rhythmic',
    frequency: 4300,
    waveform: 'sawtooth',
    attack: 0.01, decay: 0.08, sustain: 0.12, release: 0.16,
    lfoRate: 15.9, lfoDepth: 140, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 3000, Q: 2 },
  },
  {
    name: 'cicada-rhythm-f',
    mode: 'rhythmic',
    frequency: 3600,
    waveform: 'square',
    attack: 0.016, decay: 0.14, sustain: 0.2, release: 0.24,
    lfoRate: 11.1, lfoDepth: 120, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 3800, Q: 10 },
  },

  // ── RHYTHMIC WOODPECKER KNOCKS (6 VARIANTS) ──────────────────────────────
  {
    name: 'woodpecker-rhythm-a',
    mode: 'rhythmic',
    frequency: 420,
    waveform: 'triangle',
    attack: 0.003, decay: 0.08, sustain: 0.02, release: 0.12,
    lfoRate: 7.4, lfoDepth: 126, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 520, Q: 11 },
  },
  {
    name: 'woodpecker-rhythm-b',
    mode: 'rhythmic',
    frequency: 520,
    waveform: 'sawtooth',
    attack: 0.004, decay: 0.1, sustain: 0.04, release: 0.14,
    lfoRate: 8.8, lfoDepth: 132, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 640, Q: 10 },
  },
  {
    name: 'woodpecker-rhythm-c',
    mode: 'rhythmic',
    frequency: 300,
    waveform: 'triangle',
    attack: 0.006, decay: 0.14, sustain: 0.08, release: 0.2,
    lfoRate: 5.1, lfoDepth: 104, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 360, Q: 8 },
  },
  {
    name: 'woodpecker-rhythm-d',
    mode: 'rhythmic',
    frequency: 680,
    waveform: 'sawtooth',
    attack: 0.003, decay: 0.06, sustain: 0.01, release: 0.1,
    lfoRate: 9.9, lfoDepth: 138, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 760, Q: 12 },
  },
  {
    name: 'woodpecker-rhythm-e',
    mode: 'rhythmic',
    frequency: 260,
    waveform: 'triangle',
    attack: 0.008, decay: 0.18, sustain: 0.12, release: 0.26,
    lfoRate: 3.6, lfoDepth: 96, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 300, Q: 7 },
  },
  {
    name: 'woodpecker-rhythm-f',
    mode: 'rhythmic',
    frequency: 590,
    waveform: 'sawtooth',
    attack: 0.004, decay: 0.09, sustain: 0.03, release: 0.15,
    lfoRate: 8.1, lfoDepth: 128, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 340, Q: 1.3 },
  },

  // ── RHYTHMIC OCEAN SWELLS (6 VARIANTS) ────────────────────────────────────
  {
    name: 'ocean-rhythm-a',
    mode: 'rhythmic',
    frequency: 70,
    waveform: 'sine',
    attack: 0.9, decay: 1.6, sustain: 0.36, release: 2.4,
    lfoRate: 0.22, lfoDepth: 112, lfoTarget: 'amplitude',
    filter: { type: 'lowpass', freq: 220, Q: 0.8 },
  },
  {
    name: 'ocean-rhythm-b',
    mode: 'rhythmic',
    frequency: 95,
    waveform: 'triangle',
    attack: 0.7, decay: 1.2, sustain: 0.28, release: 1.9,
    lfoRate: 0.31, lfoDepth: 108, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 240, Q: 1.1 },
  },
  {
    name: 'ocean-rhythm-c',
    mode: 'rhythmic',
    frequency: 130,
    waveform: 'triangle',
    attack: 0.5, decay: 1.1, sustain: 0.24, release: 1.6,
    lfoRate: 0.42, lfoDepth: 118, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 310, Q: 1.6 },
  },
  {
    name: 'ocean-rhythm-d',
    mode: 'rhythmic',
    frequency: 56,
    waveform: 'sine',
    attack: 1.2, decay: 2.0, sustain: 0.4, release: 3.1,
    lfoRate: 0.18, lfoDepth: 106, lfoTarget: 'amplitude',
    filter: { type: 'lowpass', freq: 180, Q: 0.7 },
  },
  {
    name: 'ocean-rhythm-e',
    mode: 'rhythmic',
    frequency: 180,
    waveform: 'sawtooth',
    attack: 0.35, decay: 0.8, sustain: 0.2, release: 1.2,
    lfoRate: 0.48, lfoDepth: 124, lfoTarget: 'amplitude',
    filter: { type: 'lowpass', freq: 460, Q: 0.9 },
  },
  {
    name: 'ocean-rhythm-f',
    mode: 'rhythmic',
    frequency: 220,
    waveform: 'triangle',
    attack: 0.28, decay: 0.7, sustain: 0.18, release: 1.0,
    lfoRate: 0.58, lfoDepth: 126, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 420, Q: 1.4 },
  },

  // ── RHYTHMIC BAMBOO CLICKS (6 VARIANTS) ──────────────────────────────────
  {
    name: 'bamboo-rhythm-a',
    mode: 'rhythmic',
    frequency: 360,
    waveform: 'triangle',
    attack: 0.002, decay: 0.06, sustain: 0.02, release: 0.1,
    lfoRate: 6.8, lfoDepth: 122, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 420, Q: 10 },
  },
  {
    name: 'bamboo-rhythm-b',
    mode: 'rhythmic',
    frequency: 470,
    waveform: 'triangle',
    attack: 0.003, decay: 0.08, sustain: 0.03, release: 0.11,
    lfoRate: 8.9, lfoDepth: 130, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 540, Q: 11 },
  },
  {
    name: 'bamboo-rhythm-c',
    mode: 'rhythmic',
    frequency: 620,
    waveform: 'square',
    attack: 0.003, decay: 0.07, sustain: 0.02, release: 0.1,
    lfoRate: 10.4, lfoDepth: 136, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 680, Q: 12 },
  },
  {
    name: 'bamboo-rhythm-d',
    mode: 'rhythmic',
    frequency: 810,
    waveform: 'square',
    attack: 0.002, decay: 0.05, sustain: 0.01, release: 0.08,
    lfoRate: 12.2, lfoDepth: 140, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 500, Q: 1.8 },
  },
  {
    name: 'bamboo-rhythm-e',
    mode: 'rhythmic',
    frequency: 930,
    waveform: 'sawtooth',
    attack: 0.002, decay: 0.04, sustain: 0.0, release: 0.08,
    lfoRate: 13.5, lfoDepth: 142, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 650, Q: 2.2 },
  },
  {
    name: 'bamboo-rhythm-f',
    mode: 'rhythmic',
    frequency: 340,
    waveform: 'triangle',
    attack: 0.004, decay: 0.1, sustain: 0.05, release: 0.14,
    lfoRate: 5.2, lfoDepth: 110, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 390, Q: 9 },
  },

  // ── RHYTHMIC FROG CHORUS (6 VARIANTS) ────────────────────────────────────
  {
    name: 'frog-rhythm-a',
    mode: 'rhythmic',
    frequency: 110,
    waveform: 'sine',
    attack: 0.08, decay: 0.42, sustain: 0.26, release: 0.5,
    lfoRate: 1.4, lfoDepth: 98, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 160, Q: 4 },
  },
  {
    name: 'frog-rhythm-b',
    mode: 'rhythmic',
    frequency: 140,
    waveform: 'triangle',
    attack: 0.06, decay: 0.34, sustain: 0.22, release: 0.42,
    lfoRate: 1.9, lfoDepth: 106, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 210, Q: 5 },
  },
  {
    name: 'frog-rhythm-c',
    mode: 'rhythmic',
    frequency: 95,
    waveform: 'sine',
    attack: 0.1, decay: 0.55, sustain: 0.3, release: 0.62,
    lfoRate: 1.1, lfoDepth: 94, lfoTarget: 'amplitude',
    filter: { type: 'lowpass', freq: 180, Q: 1.1 },
  },
  {
    name: 'frog-rhythm-d',
    mode: 'rhythmic',
    frequency: 175,
    waveform: 'triangle',
    attack: 0.05, decay: 0.28, sustain: 0.2, release: 0.36,
    lfoRate: 2.3, lfoDepth: 112, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 240, Q: 6 },
  },
  {
    name: 'frog-rhythm-e',
    mode: 'rhythmic',
    frequency: 220,
    waveform: 'sawtooth',
    attack: 0.04, decay: 0.22, sustain: 0.14, release: 0.28,
    lfoRate: 2.8, lfoDepth: 116, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 300, Q: 6 },
  },
  {
    name: 'frog-rhythm-f',
    mode: 'rhythmic',
    frequency: 260,
    waveform: 'triangle',
    attack: 0.03, decay: 0.18, sustain: 0.12, release: 0.24,
    lfoRate: 3.2, lfoDepth: 120, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 340, Q: 7 },
  },

  // ── GLASS & CRYSTAL DRONES (4 VARIANTS) ──────────────────────────────────
  {
    name: 'glass-halo',
    frequency: 730,
    waveform: 'sine',
    attack: 2.8, decay: 1.7, sustain: 0.62, release: 5.2,
    lfoRate: 0.19, lfoDepth: 42, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 1180, Q: 6.5 },
  },
  {
    name: 'glass-chalice',
    frequency: 960,
    waveform: 'triangle',
    attack: 3.1, decay: 1.4, sustain: 0.58, release: 5.8,
    lfoRate: 0.23, lfoDepth: 48, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 1460, Q: 7.8 },
  },
  {
    name: 'glass-prism',
    frequency: 1260,
    waveform: 'sine',
    attack: 2.4, decay: 1.1, sustain: 0.54, release: 4.9,
    lfoRate: 0.31, lfoDepth: 54, lfoTarget: 'frequency',
    filter: { type: 'highpass', freq: 980, Q: 2.4 },
  },
  {
    name: 'glass-bow',
    frequency: 1680,
    waveform: 'triangle',
    attack: 1.9, decay: 0.9, sustain: 0.5, release: 4.2,
    lfoRate: 0.42, lfoDepth: 62, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 2100, Q: 9.5 },
  },

  // ── METALLIC DRONES (4 VARIANTS) ─────────────────────────────────────────
  {
    name: 'alloy-drone',
    frequency: 98,
    waveform: 'sawtooth',
    attack: 4.2, decay: 1.8, sustain: 0.72, release: 6.4,
    lfoRate: 0.11, lfoDepth: 26, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 180, Q: 4.2 },
  },
  {
    name: 'bronze-resonator',
    frequency: 172,
    waveform: 'triangle',
    attack: 3.8, decay: 1.5, sustain: 0.68, release: 6.0,
    lfoRate: 0.14, lfoDepth: 32, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 260, Q: 5.2 },
  },
  {
    name: 'iron-plate',
    frequency: 268,
    waveform: 'sawtooth',
    attack: 2.6, decay: 1.2, sustain: 0.61, release: 5.1,
    lfoRate: 0.22, lfoDepth: 40, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 390, Q: 6.8 },
  },
  {
    name: 'steel-wire',
    frequency: 412,
    waveform: 'triangle',
    attack: 2.2, decay: 1.0, sustain: 0.57, release: 4.7,
    lfoRate: 0.29, lfoDepth: 44, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 300, Q: 1.9 },
  },

  // ── THUNDER ATMOS DRONES (4 VARIANTS) ────────────────────────────────────
  {
    name: 'thunder-roll',
    frequency: 24,
    waveform: 'sine',
    attack: 7, decay: 3.2, sustain: 0.82, release: 9.2,
    lfoRate: 0.028, lfoDepth: 6, lfoTarget: 'amplitude',
    filter: { type: 'lowpass', freq: 72, Q: 0.55 },
  },
  {
    name: 'storm-pressure',
    frequency: 35,
    waveform: 'triangle',
    attack: 6.5, decay: 2.8, sustain: 0.8, release: 8.7,
    lfoRate: 0.036, lfoDepth: 8, lfoTarget: 'amplitude',
    filter: { type: 'lowpass', freq: 92, Q: 0.62 },
  },
  {
    name: 'sub-boom',
    frequency: 52,
    waveform: 'sine',
    attack: 5.4, decay: 2.4, sustain: 0.76, release: 7.5,
    lfoRate: 0.052, lfoDepth: 10, lfoTarget: 'amplitude',
    filter: { type: 'lowpass', freq: 120, Q: 0.7 },
  },
  {
    name: 'cloud-rumble',
    frequency: 71,
    waveform: 'triangle',
    attack: 4.8, decay: 2.1, sustain: 0.73, release: 6.9,
    lfoRate: 0.069, lfoDepth: 13, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 140, Q: 1.2 },
  },

  // ── REED & AEOLIAN DRONES (4 VARIANTS) ───────────────────────────────────
  {
    name: 'reed-choir',
    frequency: 214,
    waveform: 'sine',
    attack: 3.2, decay: 1.6, sustain: 0.63, release: 5.4,
    lfoRate: 0.16, lfoDepth: 28, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 330, Q: 3.3 },
  },
  {
    name: 'canyon-flute',
    frequency: 336,
    waveform: 'triangle',
    attack: 2.9, decay: 1.3, sustain: 0.6, release: 4.8,
    lfoRate: 0.2, lfoDepth: 34, lfoTarget: 'frequency',
    filter: { type: 'bandpass', freq: 520, Q: 4.2 },
  },
  {
    name: 'dune-oon',
    frequency: 486,
    waveform: 'triangle',
    attack: 2.4, decay: 1.1, sustain: 0.56, release: 4.4,
    lfoRate: 0.27, lfoDepth: 39, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 760, Q: 5.1 },
  },
  {
    name: 'pipe-veil',
    frequency: 692,
    waveform: 'sine',
    attack: 2.1, decay: 0.95, sustain: 0.52, release: 4.1,
    lfoRate: 0.34, lfoDepth: 46, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 420, Q: 1.6 },
  },

  // ── RHYTHMIC GLASS TINKS (6 VARIANTS) ────────────────────────────────────
  {
    name: 'glass-rhythm-a',
    mode: 'rhythmic',
    frequency: 1180,
    waveform: 'sine',
    attack: 0.003, decay: 0.11, sustain: 0.03, release: 0.16,
    lfoRate: 9.8, lfoDepth: 134, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 1360, Q: 11 },
  },
  {
    name: 'glass-rhythm-b',
    mode: 'rhythmic',
    frequency: 1460,
    waveform: 'triangle',
    attack: 0.002, decay: 0.08, sustain: 0.02, release: 0.12,
    lfoRate: 12.1, lfoDepth: 140, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 1650, Q: 12 },
  },
  {
    name: 'glass-rhythm-c',
    mode: 'rhythmic',
    frequency: 1720,
    waveform: 'sine',
    attack: 0.002, decay: 0.06, sustain: 0.01, release: 0.1,
    lfoRate: 14.6, lfoDepth: 142, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 1200, Q: 3 },
  },
  {
    name: 'glass-rhythm-d',
    mode: 'rhythmic',
    frequency: 940,
    waveform: 'triangle',
    attack: 0.004, decay: 0.14, sustain: 0.05, release: 0.2,
    lfoRate: 7.3, lfoDepth: 126, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 1100, Q: 9 },
  },
  {
    name: 'glass-rhythm-e',
    mode: 'rhythmic',
    frequency: 760,
    waveform: 'triangle',
    attack: 0.005, decay: 0.18, sustain: 0.08, release: 0.24,
    lfoRate: 5.9, lfoDepth: 116, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 880, Q: 8 },
  },
  {
    name: 'glass-rhythm-f',
    mode: 'rhythmic',
    frequency: 2080,
    waveform: 'sawtooth',
    attack: 0.002, decay: 0.05, sustain: 0.01, release: 0.08,
    lfoRate: 16.4, lfoDepth: 144, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 1400, Q: 2.4 },
  },

  // ── RHYTHMIC METAL CLACKS (6 VARIANTS) ───────────────────────────────────
  {
    name: 'metal-rhythm-a',
    mode: 'rhythmic',
    frequency: 260,
    waveform: 'sawtooth',
    attack: 0.003, decay: 0.09, sustain: 0.03, release: 0.13,
    lfoRate: 8.7, lfoDepth: 132, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 340, Q: 10 },
  },
  {
    name: 'metal-rhythm-b',
    mode: 'rhythmic',
    frequency: 380,
    waveform: 'square',
    attack: 0.003, decay: 0.08, sustain: 0.02, release: 0.12,
    lfoRate: 10.2, lfoDepth: 136, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 460, Q: 11 },
  },
  {
    name: 'metal-rhythm-c',
    mode: 'rhythmic',
    frequency: 520,
    waveform: 'sawtooth',
    attack: 0.002, decay: 0.06, sustain: 0.01, release: 0.1,
    lfoRate: 12.4, lfoDepth: 140, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 640, Q: 12 },
  },
  {
    name: 'metal-rhythm-d',
    mode: 'rhythmic',
    frequency: 690,
    waveform: 'square',
    attack: 0.003, decay: 0.07, sustain: 0.02, release: 0.11,
    lfoRate: 11.6, lfoDepth: 138, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 420, Q: 1.9 },
  },
  {
    name: 'metal-rhythm-e',
    mode: 'rhythmic',
    frequency: 860,
    waveform: 'sawtooth',
    attack: 0.002, decay: 0.05, sustain: 0.01, release: 0.09,
    lfoRate: 14.1, lfoDepth: 142, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 520, Q: 2.3 },
  },
  {
    name: 'metal-rhythm-f',
    mode: 'rhythmic',
    frequency: 1120,
    waveform: 'square',
    attack: 0.002, decay: 0.045, sustain: 0.0, release: 0.08,
    lfoRate: 16.2, lfoDepth: 146, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 700, Q: 2.6 },
  },

  // ── RHYTHMIC GEOTHERMAL POPS (6 VARIANTS) ────────────────────────────────
  {
    name: 'geothermal-rhythm-a',
    mode: 'rhythmic',
    frequency: 84,
    waveform: 'sine',
    attack: 0.04, decay: 0.36, sustain: 0.18, release: 0.46,
    lfoRate: 1.8, lfoDepth: 102, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 130, Q: 3.6 },
  },
  {
    name: 'geothermal-rhythm-b',
    mode: 'rhythmic',
    frequency: 116,
    waveform: 'triangle',
    attack: 0.03, decay: 0.28, sustain: 0.15, release: 0.38,
    lfoRate: 2.4, lfoDepth: 110, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 170, Q: 4.2 },
  },
  {
    name: 'geothermal-rhythm-c',
    mode: 'rhythmic',
    frequency: 168,
    waveform: 'triangle',
    attack: 0.025, decay: 0.22, sustain: 0.13, release: 0.32,
    lfoRate: 3.1, lfoDepth: 114, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 230, Q: 4.8 },
  },
  {
    name: 'geothermal-rhythm-d',
    mode: 'rhythmic',
    frequency: 236,
    waveform: 'sawtooth',
    attack: 0.018, decay: 0.16, sustain: 0.1, release: 0.26,
    lfoRate: 3.8, lfoDepth: 118, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 320, Q: 5.2 },
  },
  {
    name: 'geothermal-rhythm-e',
    mode: 'rhythmic',
    frequency: 312,
    waveform: 'triangle',
    attack: 0.015, decay: 0.12, sustain: 0.08, release: 0.2,
    lfoRate: 4.6, lfoDepth: 124, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 410, Q: 5.9 },
  },
  {
    name: 'geothermal-rhythm-f',
    mode: 'rhythmic',
    frequency: 422,
    waveform: 'sawtooth',
    attack: 0.01, decay: 0.1, sustain: 0.06, release: 0.16,
    lfoRate: 5.4, lfoDepth: 130, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 280, Q: 1.5 },
  },

  // ── RHYTHMIC ELECTRO PULSES (6 VARIANTS) ─────────────────────────────────
  {
    name: 'electro-rhythm-a',
    mode: 'rhythmic',
    frequency: 210,
    waveform: 'square',
    attack: 0.01, decay: 0.15, sustain: 0.12, release: 0.22,
    lfoRate: 6.2, lfoDepth: 122, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 280, Q: 5.5 },
  },
  {
    name: 'electro-rhythm-b',
    mode: 'rhythmic',
    frequency: 320,
    waveform: 'square',
    attack: 0.008, decay: 0.12, sustain: 0.1, release: 0.18,
    lfoRate: 7.4, lfoDepth: 128, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 420, Q: 6.2 },
  },
  {
    name: 'electro-rhythm-c',
    mode: 'rhythmic',
    frequency: 460,
    waveform: 'sawtooth',
    attack: 0.006, decay: 0.1, sustain: 0.08, release: 0.15,
    lfoRate: 8.9, lfoDepth: 134, lfoTarget: 'amplitude',
    filter: { type: 'bandpass', freq: 590, Q: 7.2 },
  },
  {
    name: 'electro-rhythm-d',
    mode: 'rhythmic',
    frequency: 620,
    waveform: 'square',
    attack: 0.005, decay: 0.09, sustain: 0.06, release: 0.13,
    lfoRate: 10.8, lfoDepth: 138, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 360, Q: 2.1 },
  },
  {
    name: 'electro-rhythm-e',
    mode: 'rhythmic',
    frequency: 780,
    waveform: 'sawtooth',
    attack: 0.004, decay: 0.07, sustain: 0.04, release: 0.11,
    lfoRate: 12.6, lfoDepth: 142, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 440, Q: 2.4 },
  },
  {
    name: 'electro-rhythm-f',
    mode: 'rhythmic',
    frequency: 980,
    waveform: 'square',
    attack: 0.003, decay: 0.06, sustain: 0.02, release: 0.1,
    lfoRate: 14.2, lfoDepth: 146, lfoTarget: 'amplitude',
    filter: { type: 'highpass', freq: 520, Q: 2.8 },
  },
];
